name: Build documentation

on:
  push:
    branches:
      - main
      - test-ci*
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  push_doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable 

      - run: pip install .[doc]

      - name: Create env file
        run: |
          touch .env
          echo GROQ_API_KEY='${{ secrets.GROQ_API_KEY }}' >> .env
          echo LOGFIRE_TOKEN='${{ secrets.LOGFIRE_TOKEN }}' >> .env
          echo OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' >> .env

      - name: Sphinx build
        run: sphinx-build doc build

      - name: Save the PR number
        env:
          GITHUB_PULL_REQUEST_NUMBER: ${{github.event.number}}
        run: |
          echo "Storing PR number ${{github.event.number}} to 'pull_request_number' file"
          echo ${{github.event.number}} > pull_request_number

      - name: Upload doc preview
        # The publication of the preview itself happens in pr-doc-preview.yml
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: doc-preview
          path: |
            ./build
            pull_request_number

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: "[ci skip] ${{ github.event.head_commit.message }}"
